from pathlib import Path
from datetime import datetime

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent

README_PATH = PROJECT_ROOT / "README.md"
GITIGNORE_PATH = PROJECT_ROOT / ".gitignore"
PRODUCT_DEFINITION_PATH = PROJECT_ROOT / "docs" / "PRODUCT_DEFINITION.md"
REPORT_PATH = SCRIPT_DIR / "developerpatchscript_report.txt"


README_CONTENT = """# Philotes

**A Community for Friendship**

**Brought to you by Titan**

Philotes is a friendship and community platform being developed by Titan.

The purpose of Philotes is to help adults discover people with shared interests,
build genuine friendships, participate in activities, and form meaningful social
connections in a safety-focused community.

## Project Status

Philotes is currently in initial product definition and development.

## Planned Client Platforms

- Android
- iOS
- Windows
- macOS
- Web where appropriate

## Initial Technology Direction

- Flutter / Dart for client applications
- Python / FastAPI for backend services
- PostgreSQL for relational data
- Git / GitHub for source control

## Brand

PHILOTES

A Community for Friendship

Brought to you by Titan
"""


GITIGNORE_CONTENT = """# Philotes repository exclusions

# Environment files and secrets
.env
.env.*
!.env.example

# Python
__pycache__/
*.py[cod]
*.pyo
.venv/
venv/
.pytest_cache/
.mypy_cache/
.ruff_cache/

# Flutter / Dart
.dart_tool/
.packages
.pub-cache/
.pub/
build/
flutter_export_environment.sh

# Android
.gradle/
local.properties
*.jks
*.keystore
key.properties

# Apple / macOS
Pods/
DerivedData/
*.xcuserstate

# Visual Studio / Windows
.vs/
*.user
*.suo

# VS Code local settings
.vscode/

# Node
node_modules/

# Database/local runtime data
*.db
*.sqlite
*.sqlite3

# Logs and temporary files
*.log
*.tmp
*.temp
.DS_Store
Thumbs.db
"""


PRODUCT_DEFINITION_CONTENT = """# Philotes Product Definition

## Product Name

Philotes

## Tagline

A Community for Friendship

## Attribution

Brought to you by Titan

## Product Purpose

Philotes is a friendship-focused community platform designed to help adults
find people with compatible interests, establish genuine friendships, and
participate in activities together.

Philotes is not intended to be a dating application.

## Core Principles

1. Friendship before popularity.
2. Safety and trust are fundamental product requirements.
3. Members should be authentic and appropriately verified.
4. Initial real-world meetings should encourage safe public environments.
5. Members control their personal information.
6. The product will not depend on third-party advertising.
7. The interface should encourage genuine social connection rather than
   addictive engagement mechanics.

## Initial Community Vocabulary

- Philotes: the overall community.
- Circle: a member's friendship network or interest-based group.
- Discover: finding compatible people and communities.
- Gathering: an activity or meetup.
- First Gathering: an initial structured public meetup.
- Titan Verified: planned verified-member status.
- Trust & Safety: moderation, reporting, and member-protection functions.
- Community Standards: behavioral expectations for members.

## Initial Target Platforms

- Android
- iOS
- Windows
- macOS
- Web where appropriate

## Initial Technical Direction

### Client

Flutter and Dart.

### Backend

Python and FastAPI.

### Database

PostgreSQL.

### Source Control

Git with GitHub remote repository.

## Development Status

Phase 0 - Repository foundation and product definition.

No production application code has been created yet.
"""


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> None:
    print("=" * 70)
    print("PHILOTES DEVELOPMENT PATCH SCRIPT")
    print("=" * 70)
    print()
    print(f"Project root: {PROJECT_ROOT}")
    print()

    write_file(README_PATH, README_CONTENT)
    write_file(GITIGNORE_PATH, GITIGNORE_CONTENT)
    write_file(PRODUCT_DEFINITION_PATH, PRODUCT_DEFINITION_CONTENT)

    checks = {
        "README.md": README_PATH.exists(),
        ".gitignore": GITIGNORE_PATH.exists(),
        "docs/PRODUCT_DEFINITION.md": PRODUCT_DEFINITION_PATH.exists(),
    }

    report_lines = [
        "PHILOTES DEVELOPMENT PATCH REPORT",
        "=" * 70,
        f"Generated: {datetime.now().isoformat(timespec='seconds')}",
        f"Project root: {PROJECT_ROOT}",
        "",
        "FILES:",
    ]

    all_passed = True

    for name, passed in checks.items():
        status = "PASS" if passed else "FAIL"
        report_lines.append(f"{status}: {name}")
        print(f"{status}: {name}")

        if not passed:
            all_passed = False

    report_lines.extend(
        [
            "",
            f"OVERALL: {'PASS' if all_passed else 'FAIL'}",
            "",
            "No Flutter application code was generated by this patch.",
        ]
    )

    REPORT_PATH.write_text("\n".join(report_lines) + "\n", encoding="utf-8")

    print()
    print(f"Report: {REPORT_PATH}")
    print()
    print(f"OVERALL: {'PASS' if all_passed else 'FAIL'}")

    if not all_passed:
        raise SystemExit(1)


if __name__ == "__main__":
    main()