"""add session device metadata

Revision ID: 6c1ac54d4e15
Revises: 42fd237a90cb
Create Date: 2026-08-15 17:23:33.420663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1ac54d4e15'
down_revision: Union[str, Sequence[str], None] = '42fd237a90cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('device_name', sa.String(length=120), nullable=True))
    op.add_column('user_sessions', sa.Column('platform', sa.String(length=50), nullable=True))
    op.add_column('user_sessions', sa.Column('client_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'client_name')
    op.drop_column('user_sessions', 'platform')
    op.drop_column('user_sessions', 'device_name')
    # ### end Alembic commands ###
